### ISSUE TITLE
Indent after backslash continuation

### ISSUE THREAD

**Issue by anntzer** [Vimjas/vim-python-pep8-indent#114]
As of 5f4184f, this plugin would insert a 4-space indent after a backslash line continuation
```
with foo, \
    bar:
```
As of master there is no more indent
```
with foo, \
bar:
```
Could it be restored?  Thanks!
(Yes, backslash indents are not particularly liked in general, but they are still useful in some cases, e.g. `with` statements.)

**Comment by blueyed** [comment]
Thanks for the report.

Tested this quickly and it indents as follows for me:
```
with foo, \
        bar:
```

What settings are you using?

**Comment by blueyed** [comment]
Looking at https://github.com/Vimjas/vim-python-pep8-indent/commit/5f4184fb1200b329e810c1e4c866c86fdf44c135 it might be related to previous parenthesis (i.e. code before this)?!

**Comment by anntzer** [comment]
Actually I realized that the undesired behavior only occurs when https://github.com/vim-python/python-syntax is also loaded.  Not sure where the interaction comes from, as that plugin *should*(?) only define syntax elements...

**Comment by blueyed** [comment]
Can you git-bisect it, please?
Might be due to https://github.com/Vimjas/vim-python-pep8-indent/commit/d9efc9643da118f0928f204d2c5d3ce0e987eb44.

**Comment by blueyed** [comment]
Thanks for the report, should be fixed now.
