### ISSUE TITLE
Incorrect indentation for functions with end paren on a separate line.

### ISSUE THREAD

**Issue by deiden26** [Vimjas/vim-python-pep8-indent#126]
Before auto indentation

```
def do_thing(
    argument_1,
    argument_2
):
```

After auto indentation
```
def do_thing(
        argument_1,
        argument_2
):
```

There is no reason for the extra indentation if the argument list's closing parenthesis is on its own line.

**Comment by blueyed** [comment]
Thanks for the report.  See https://github.com/Vimjas/vim-python-pep8-indent/pull/127.

Not sure if this won't break other things - at least it was testing for this behavior previously.

JFI: it is only looking upward, so it does not matter if the closing paren is on the first level / not indented - but it will indent like you expect it to.

**Comment by deiden26** [comment]
Thanks

**Comment by deiden26** [comment]
Just a heads up, this change results in the following auto indentation

```
def thing(
    stuff):
    return stuff

```

Which should be 

```
def thing(
        stuff):
    return stuff
```

per https://www.python.org/dev/peps/pep-0008/#indentation

```
# Add 4 spaces (an extra level of indentation) to distinguish arguments from the rest.
def long_function_name(
        var_one, var_two, var_three,
        var_four):
    print(var_one)
```

This is why I mentioned the end parenthesis specifically. In the case where the ending parenthesis is on the same line as the last argument, the double indentation is correct.

**Comment by blueyed** [comment]
I see.
However, then we cannot really fix this - at least while typing (without the closing parenthesis being there already), no?
It would indent with 8 spaces, and adding the closing one on a new line would not re-indent the line above - you would have to indent it manually again.

**Comment by deiden26** [comment]
> It would indent with 8 spaces, and adding the closing one on a new line would not re-indent the line above - you would have to indent it manually again.

That would be satisfactory to me. Even if the indentation doesn't work as I type, it would be nice if when I select a block like this and auto-indent it

```
def do_thing(
        stuff
):
```

I'd get this

```
def do_thing(
    stuff
):
```

By the way, I really appreciate you taking the time to look into this and converse with me.

**Comment by blueyed** [comment]
:+1: 
I think it can even be done while typing (when pressing ":" (via `indentkeys`).  See #129.

**Comment by blueyed** [comment]
With `:set indentkeys+=*<Return>` it would even handle

```
def func(
        bar_)
```
to
```
def func(
    bar
)
```
(with the cursor at `_` and pressing `<CR>`)
But I do not think it is worth adding this by default.

**Comment by blueyed** [comment]
Let me know how it works for you, happy to follow up more on this.. :)

**Comment by deiden26** [comment]
This is beautiful. Thanks again for being so responsive.

**Comment by blueyed** [comment]
You're welcome - thanks for the detailed report in the first place.. :)

Initially I've thought that it should look for the matching closing parenthesis via `searchpairpos` also (forward, stopping at the next line (or at least fast) then), which might be more robust after all.
I guess currently it might handle trailing whitespace not good enough for example etc.

Let me know any findings, and we can have more tests / fixes here.. ;)

**Comment by blueyed** [comment]
Hope it's working well still.. :)

Just found that this also should be handled for type annotations in a similar way / just for reference: https://github.com/Vimjas/vim-python-pep8-indent/issues/130

**Comment by zachliu** [comment]
PEP8 [indentation](https://www.python.org/dev/peps/pep-0008/#indentation) style is funny. 
```
def do_thing(
        argument_1,
        argument_2
):
```
But I still think the above looks a bit better than
```
def do_thing(
    argument_1,
    argument_2
):
```
or
```
def do_thing(
        argument_1,
        argument_2):
```
:smile: :smile: :smile:

**Comment by blueyed** [comment]
So you prefer 1 over 2?

IIRC this was changed to use 2 instead of 1 here.

**Comment by zachliu** [comment]
Yeah, I know, it's just my preference. I use 
```
def do_thing(
        argument_1,
        argument_2
):
```
in function/class definitions, and use
```
do_thing(
    argument_1,
    argument_2
)
```
when I'm calling them.

**Comment by jonathf** [comment]
There doesn't seem to be a consensus on this topic. The pylint team seams to be against this:
https://github.com/PyCQA/pylint/issues/1651
I don't care what it should be, but I don't like that my linter and my editor disagreeing.

I don't know if this goes against the spirit of this plugin, but would it be possible to parameterize this feature using a global flag? Like `let g:python_pep8_double_indentation = 1`, such that we can have our cake and eat it too?

I would be happy to make the PR, if there if the maintainers don't mind.
