### ISSUE TITLE
'elif' indentation is forced to deepest 'if' one

### ISSUE THREAD

**Issue by dff9th** [Vimjas/vim-python-pep8-indent#135]
'elif' indentation is forced to deepest 'if' one as follows.
before indent:
```
if True:
    if True:
        pass
elif:
    pass
```
after indent:
```
if True:
    if True:
        pass
    elif:
        pass
```
expected after indent:
```
if True:
    if True:
        pass
elif:
    pass
```

On the other hand, 'else' indentation performs as I expected.
before indent:
```
if True:
    if True:
        pass
else:
    pass
```
after indent:
```
if True:
    if True:
        pass
else:
    pass
```

**Comment by blueyed** [comment]
Thanks for the report - I've noticed this myself, but now took the time to fix it: https://github.com/Vimjas/vim-python-pep8-indent/pull/136.

**Comment by asmka** [comment]
Thank you for your quick fixing.
I confirmed expected behavior.
