### ISSUE TITLE
System wide installation

### ISSUE THREAD

**Issue by bergentroll** [Vimjas/vim-python-pep8-indent#139]
I would like to make a package for Archlinux AUR, so I tried to install vim-python-pep8-indent system wide. I tried to put [python.vim](../blob/master/indent/python.vim) into the `/usr/share/vim/vimfiles/indent/`, but it does not work in such way. So I tried to put it into the `/usr/share/vim/vimfiles/after/indent/`, but it does not work too. I also tried to cut `if exists('b:did_indent')` statement to test, but it changes nothing. Therefore things work smoothely with Plug package manager or also when I manually source the python.vim.

Is such behaviour presented by design? I there a way to install script globally?

**Comment by blueyed** [comment]
I think putting it into `/usr/share/vim/vimfiles/indent/` should work in general.
Check `:scriptnames` and e.g. add something like `unsilent echom "Loaded"` there to see if it gets sourced in the first place.

**Comment by bergentroll** [comment]
Indeed, it works with `neovim` and it works with `vim --clean`. But `python.vim` has not been even loaded with plain `vim some_file.py` run, even when `~/.vimrc` is empty. Seems like some specific case. Great thank you, @blueyed, I'll try to investigate it a bit deeper.

**Comment by bergentroll** [comment]
Fine, due to documentation Vim >= 8.0 needs manual sourcing of default config in `.vimrc` like this:
```vim
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim
```

Out of the box `defaults.vim` is being sourced only if `~/.vimrc` is not presented.
