### ISSUE TITLE
Different textwidth / line length with comments / docstrings

### ISSUE THREAD

**Issue by blueyed** [Vimjas/vim-python-pep8-indent#31]
From http://legacy.python.org/dev/peps/pep-0008/#maximum-line-length:

> Maximum Line Length
> 
> Limit all lines to a maximum of 79 characters.
> 
> For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.

I have found a Vimscript on StackOverflow to support this:
http://stackoverflow.com/a/4028423/15690

I think this would be a great fit for this plugin.
What do you think?

_edit_: ok, I've just noticed that this plugin is only about indentation and it does not really fit in here, so please feel free to close it.

Reported for vim-python-mode at https://github.com/klen/python-mode/issues/461.

**Comment by danijar** [comment]
+1

**Comment by blueyed** [comment]
Closing due to being out of scope for an indentation plugin.
