### ISSUE TITLE
Idents do not work if <CR> between open-paren and close-paren with no args 

### ISSUE THREAD

**Issue by cmcginty** [Vimjas/vim-python-pep8-indent#65]
If I have the following line:

```
def main()
```

and I try to `<CR>` between the parens I get:

```
def main(
)
```

If there are arguments on the first line, it works as expected. For example:

```
def main(one,)
```

If the cursor is right after the comma, a `<CR>` results in:

```
def main(one,
         )
```

**Comment by purpleP** [comment]
@cmcginty I'm not sure, but it's probably supposed to be this way, because if you want this particular feature you need to install something like delimitMate. Notice that if you would press `O` at the `)` it would insert correct level of indentation.

**Comment by blueyed** [comment]
Not sure myself, but closing as works-as-expected for now.
