### ISSUE TITLE
cython support

### ISSUE THREAD

**Issue by tgy** [Vimjas/vim-python-pep8-indent#73]
I'm writing cython code and would like to use the same indentation.

Is there a simple solution to enable this plugin on cython files?

**Comment by blueyed** [comment]
Should be there: https://github.com/Vimjas/vim-python-pep8-indent/pull/48 in general.

Is your `&filetype` `cython`?
Try `runtime indent/python.vim` then.

I think we could have a symlink `indent/cython.vim => python.vim`?!

/cc @anntzer

**Comment by tgy** [comment]
I have `filetype=cython` defined by [tshirtman/vim-cython](https://github.com/tshirtman/vim-cython).

`runtime indent/ython.vim` and the `indent/cython.vim > python.vim` symlink do work! Thanks for that.

**Comment by blueyed** [comment]
I think a symlink should be enough.
Can you confirm that (i.e. try #74), please?

**Comment by tgy** [comment]
@blueyed sorry I forgot to answer last time. I confirm the symlink solution solves the problem. :) Thank you for your help
