### ISSUE TITLE
cc doesn't auto-indent blank lines within a block

### ISSUE THREAD

**Issue by gandalf3** [Vimjas/vim-python-pep8-indent#77]
Test case: (`*` represents cursor position)
```
def a():
    b = 42
    c = "asdf"
*
    # random stuff
```

Pressing `cc` with `indentexpr=cindent(v:lnum)` gives the expected result:

```
def a():
    b = 42
    c = "asdf"
    *
    # random stuff
```

With `indentexpr=GetPythonPEPIndent(v:lnum)` however, the cursor remains on column 1:

```
def a():
    b = 42
    c = "asdf"
*
    # random stuff
```

**Comment by aldanor** [comment]
Also, in this example:

```python
def a():
    b = 42
    c = "asdf"
*
    # random stuff
```

Pressing <CR> in insert mode results in 

```python
def a():
    b = 42
    c = "asdf"

*
    # random stuff
```

which is quite unfortunate :(

**Comment by aldanor** [comment]
This also extrapolates to the nested case:

```python
def a():
    'foo'

    def b():
        'bar'
*
        'baz'
```

Pressing `<CR>` in insert mode:

```python
def a():
    'foo'

    def b():
        'bar'

*
        'baz'
```
