### ISSUE TITLE
Suggestion: delete the space in the end when break a line

### ISSUE THREAD

**Issue by CareF** [Vimjas/vim-python-pep8-indent#96]
Thank you a lot for making a very nice plugin, but sorry I don't have the ability to implement it myself. 
The conditions are: 

    foo(a, b, c)

and I want to break after `b, `, I would expect for same result no matter I break the line after `,` or space.

**Comment by blueyed** [comment]
Makes sense, but it does not seem the responsibility of an indent plugin to change text by itself.
We're only being asked for the indent of line 2 in this case - and should not modify line 1.

I am closing this, and suggest to use something to remove trailing spaces instead and/or just wrap after the `,`.. ;)
